export const coastguard = [
  {
    name: 'Director General ',
    number: '1769440000',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to DG',
    number: '1769440001',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff DG Office',
    number: '1769440005',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'DG Secretary ',
    number: '1769440010',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to DG Secretary',
    number: '1769440011',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Flag Lt',
    number: '1769440014',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff DG secretary office',
    number: '1769440015',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'CG Secretary',
    number: '1769440020',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to CG Secretary',
    number: '1769440021',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff CG secretary office',
    number: '1769440025',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'JAG',
    number: '1769440040',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to JAG',
    number: '1769440041',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Law Officer',
    number: '1769440042',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff JAG office',
    number: '1769440045',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'CI & QC',
    number: '1769440060',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to CI & QC',
    number: '1769440061',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'AD CI & QC',
    number: '1769440063',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff CI & QC office',
    number: '1769440065',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: ' President CGFWA',
    number: '1769440080',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Vice president CGFWA',
    number: '1769440081',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Treasurer',
    number: '1769440082',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff CGFWA office',
    number: '1769440085',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director General',
    number: '1769440200',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to DDG',
    number: '1769440201',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff DDG office',
    number: '1769440205',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Director Opration',
    number: '1769440300',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to D/ Operation',
    number: '1769440301',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Operation',
    number: '1769440302',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Operation',
    number: '1769440303',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Operation',
    number: '1769440333',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff OPS',
    number: '1769440305',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'OPS Room',
    number: '1769440999',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Director Plans & Acquisition',
    number: '1769440350',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to Director Plans & Acquisition',
    number: '1769440351',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Plans',
    number: '1769440352',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Plans',
    number: '1769440353',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Plans',
    number: '1769440354',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Plans',
    number: '1769440355',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Acquisition',
    number: '1769440362',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Directo Acquisition',
    number: '1769440363',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Acquisition',
    number: '1769440364',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Director Personnel',
    number: '1769440400',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to Director Personnel',
    number: '1769440401',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Personnel',
    number: '1769440402',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Personnel',
    number: '1769440403',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Personnel',
    number: '1769440404',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Pers',
    number: '1769440405',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Training',
    number: '1769440412',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Training',
    number: '1769440413',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Training',
    number: '1769440414',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff traning',
    number: '1769440415',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Medical',
    number: '1769440422',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Medical',
    number: '1769440423',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Medical',
    number: '1769440424',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'OIC Welfare Found',
    number: '1769440430',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Welfare Found',
    number: '1769440435',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Director Engineer',
    number: '1769440450',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to Director Engineer',
    number: '1769440451',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Engineer',
    number: '1769440452',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Engineer',
    number: '1769440453',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Engineer',
    number: '1769440454',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Office staff',
    number: '1769440455',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Works',
    number: '1769440462',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Works',
    number: '1769440463',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Works',
    number: '1769440464',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Electrical',
    number: '1769440473',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Electrical',
    number: '1769440474',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Director Logistics',
    number: '1769440500',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to Logistics',
    number: '1769440501',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Budget',
    number: '1769440502',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Budget',
    number: '1769440503',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Budget',
    number: '1769440504',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Budget Staff',
    number: '1769440505',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Account',
    number: '1769440512',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Account',
    number: '1769440513',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Offier Account',
    number: '1769440514',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Store',
    number: '1769440523',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Store',
    number: '1769440524',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Store',
    number: '1769440525',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Teachnical Store',
    number: '1769440532',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Teachnical ',
    number: '1769440533',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Teachnical Store',
    number: '1769440534',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff TS',
    number: '1769440535',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Director Intelligence',
    number: '1769440550',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to Intelligence',
    number: '1769440551',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Intelligence',
    number: '1769440552',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Intelligence',
    number: '1769440553',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Intelligence',
    number: '1769440554',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Intelligence Office',
    number: '1769440555',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Int (Passport & Visa)',
    number: '1769440556',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Int (Press & Media)',
    number: '1769440557',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Int',
    number: '1769440558',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Int',
    number: '1769440559',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Director IT & Communication',
    number: '1769440900',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'PA to IT & Communication',
    number: '1769440901',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director IT',
    number: '1769440902',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director IT',
    number: '1769440903',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer IT',
    number: '1769440904',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff IT',
    number: '1769440905',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Communication',
    number: '1769440612',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Communication',
    number: '1769440613',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Communication',
    number: '1769440614',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Comsen',
    number: '1769440615',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Deputy Director Exchange & Server',
    number: '1769440622',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Assistant Director Exchange & Server',
    number: '1769440623',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Staff Officer Exchange & Server',
    number: '1769440624',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Exchange Staff',
    number: '1769440644',
    address: 'Headquarter',
    estd: '',
  },
  {
    name: 'Comcen',
    number: '1769440666',
    address: 'Headquarter',
    estd: '',
  },

  {
    name: 'Zonal Commander',
    number: '1769441000',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'PA to Zonal Commander',
    number: '1769441001',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'CSO (Admin)',
    number: '1769441005',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: "Senior Officer Shop's & Craft",
    number: '1769441010',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Staff Officer OPS',
    number: '1769441333',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Staff OPS',
    number: '1769441016',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'OPS Room',
    number: '1769441999',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Plan',
    number: '1769441020',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Staff Officer LAW',
    number: '1769441025',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Traning',
    number: '1769441030',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Engineering',
    number: '1769441035',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Electrical & Armaments',
    number: '1769441040',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Logistics',
    number: '1769441045',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'OIC Intelligence',
    number: '1769441050',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff',
    number: '1769441051',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff',
    number: '1769441052',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff',
    number: '1769441053',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff',
    number: '1769441054',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Intelligence Office',
    number: '1769441055',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Tender',
    number: '1769441060',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Staff Officer signals',
    number: '1769441065',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Comsen  ',
    number: '1769441066',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Incharge Comcen',
    number: '1769441067',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Public Relation Officer',
    number: '1769441070',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Anti smagling Officer',
    number: '1769441075',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Treasurer',
    number: '1769441082',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Staff CGFWA office',
    number: '1769441085',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'CGPM/Staff Officer Provost',
    number: '1769441090',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-1',
    number: '1769441091',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-2 ',
    number: '1769441092',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-3 ',
    number: '1769441093',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Duty DR ',
    number: '1769441094',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'CGPM Office',
    number: '1769441095',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Mail man',
    number: '1769441099',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Commanding Officer',
    number: '1769441100',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'CO Secretery ',
    number: '1769441101',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'CO Secretery Office',
    number: '1769441102',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Exicutive Officer',
    number: '1769441105',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'EXO Staff',
    number: '1769441106',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Chief Boson Met',
    number: '1769441107',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Boson yeo man',
    number: '1769441108',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Gunnery Officer',
    number: '1769441112',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Ships GI',
    number: '1769441113',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Gunnery Office',
    number: '1769441114',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Regulating Officer',
    number: '1769441115',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Regulating Office',
    number: '1769441116',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Engineering Officer',
    number: '1769441118',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Engineering Office',
    number: '1769441119',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'EO Writer',
    number: '1769441120',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Electrical Officer',
    number: '1769441122',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Electrical Office',
    number: '1769441123',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'LO Writer',
    number: '1769441124',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Maintainance Officer',
    number: '1769441126',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Maintainance Office',
    number: '1769441127',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Senior Medical Officer',
    number: '1769441130',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Medical Officer',
    number: '1769441131',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Ward Master',
    number: '1769441132',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Sick Bay',
    number: '1769441133',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Duty Medical Assistant',
    number: '1769441134',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Supply Officer',
    number: '1769441135',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Store Office ',
    number: '1769441136',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Pay Office',
    number: '1769441137',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Officer In Charge (Boat Pool)',
    number: '1769441140',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Boat Pool (cpo/po)',
    number: '1769441141',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Boat Pool',
    number: '1769441142',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Incharge Exchange & Server',
    number: '1769441143',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Exchange & Server Room',
    number: '1769441144',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'MTO',
    number: '1769441145',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'MT Chief',
    number: '1769441146',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'MT Pool ',
    number: '1769441147',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Ward Room Mess Secretery',
    number: '1769441148',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Duty STW',
    number: '1769441149',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Mess OIC',
    number: '1769441150',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Mess Secretery',
    number: '1769441151',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'SOOD',
    number: '1769441111',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'OOD ',
    number: '1769441160',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'CPOOD/POOD',
    number: '1769441165',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Guard Room',
    number: '1769441166',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Station Commander Pagla',
    number: '1769441200',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Exicutive Officer Pagla',
    number: '1769441201',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Pagla',
    number: '1769441205',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Gangway Pagla',
    number: '1769441209',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Station Commander Chandpur',
    number: '1769441210',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'EXO Chandpur ',
    number: '1769441211',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Chandpur',
    number: '1769441215',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Gangway Chandpur',
    number: '1769441219',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Station Commander Padma',
    number: '1769441220',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'EXO Padma',
    number: '1769441221',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Padma',
    number: '1769441225',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Gangway Padma',
    number: '1769441229',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Station Commander Gozaria',
    number: '1769441230',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Exo Gozaria',
    number: '1769441231',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Gozaria',
    number: '1769441235',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Gangway Gozaria',
    number: '1769441239',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Station Commander Hymchar',
    number: '1769441240',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'EXO Hymchar  ',
    number: '1769441241',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Hymchar',
    number: '1769441245',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Gangway Hymchar',
    number: '1769441249',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'OIC CGS Rangamati',
    number: '1769441500',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Rangamati',
    number: '1769441501',
    address: 'Dhaka Zone',
    estd: '',
  },
  {
    name: 'Zonal Commander',
    number: '1769442000',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'PA to Zonal Commander',
    number: '1769442001',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CSO (Admin)    ',
    number: '1769442005',
    address: 'East Zone',
    estd: '',
  },
  {
    name: "Senior Officer Shop's & Craft   ",
    number: '1769442010',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Staff Officer OPS    ',
    number: '1769442333',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Staff OPS      ',
    number: '1769442016',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'OPS Room       ',
    number: '1769442999',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Plans  ',
    number: '1769442020',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Staff Officer LAW    ',
    number: '1769442025',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Traning',
    number: '1769442030',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Engineering       ',
    number: '1769442035',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Electrical & Arma ',
    number: '1769442040',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Logistics         ',
    number: '1769442045',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'OIC Intelligence     ',
    number: '1769442050',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff   ',
    number: '1769442051',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff   ',
    number: '1769442052',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff   ',
    number: '1769442053',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff   ',
    number: '1769442054',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Office  ',
    number: '1769442055',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Tender ',
    number: '1769442060',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Staff Officer signals',
    number: '1769442065',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Comsen         ',
    number: '1769442066',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Incharge Comsen',
    number: '1769442067',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Public Relation Officer         ',
    number: '1769442070',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Anti smagling Officer',
    number: '1769442075',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Area chairman CGFWA',
    number: '1769441080',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Treasurer      ',
    number: '1769442082',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Staff CGFWA office   ',
    number: '1769442085',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CGPM/Staff Officer Provost      ',
    number: '1769442090',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-1   ',
    number: '1769442091',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-2   ',
    number: '1769442092',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-3   ',
    number: '1769442093',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Duty DR        ',
    number: '1769442094',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CGPM Office    ',
    number: '1769442095',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Mail man       ',
    number: '1769442099',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Commanding Officer   ',
    number: '1769442100',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CO Secretery   ',
    number: '1769442101',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CO Secretery Office  ',
    number: '1769442102',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Exicutive Officer    ',
    number: '1769442105',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EXO Staff      ',
    number: '1769442106',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Chief Boson Met',
    number: '1769442107',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Boson yeo man  ',
    number: '1769442108',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'OOD ',
    number: '1769442111',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gunnery Officer',
    number: '1769442112',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Ships GI       ',
    number: '1769442113',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gunnery Office ',
    number: '1769442114',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Regulating Officer   ',
    number: '1769442115',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Regulating Office    ',
    number: '1769442116',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Engineering Officer  ',
    number: '1769442118',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Engineering Office   ',
    number: '1769442119',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EO Writer      ',
    number: '1769442120',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Electrical Officer   ',
    number: '1769442122',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Electrical Office    ',
    number: '1769442123',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'LO Writer      ',
    number: '1769442124',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Maintainance Officer ',
    number: '1769442126',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Maintainance Office  ',
    number: '1769442127',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Senior Medical Officer          ',
    number: '1769442130',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Medical Officer',
    number: '1769442131',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Ward Master    ',
    number: '1769442132',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Sick Bay       ',
    number: '1769442133',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Duty Medical Assistant          ',
    number: '1769442134',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Supply Officer ',
    number: '1769442135',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Store Office   ',
    number: '1769442136',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Pay Office     ',
    number: '1769442137',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Officer In Charge (Boat Pool)   ',
    number: '1769442140',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Boat Pool (cpo/po)   ',
    number: '1769442141',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Boat Pool      ',
    number: '1769442142',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Incharge Exchange & Server      ',
    number: '1769442143',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Exchange & Server Room          ',
    number: '1769442144',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'MTO ',
    number: '1769442145',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'MT Chief       ',
    number: '1769442146',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'MT Pool        ',
    number: '1769442147',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Ward Room Mess Secretery        ',
    number: '1769442148',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Duty STW       ',
    number: '1769442149',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Mess OIC       ',
    number: '1769442150',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Mess Secretery ',
    number: '1769442151',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CPOOD/POOD     ',
    number: '1769442165',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Guard Room     ',
    number: '1769442166',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Sangu         ',
    number: '1769442200',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff   ',
    number: '1769442205',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Sangu  ',
    number: '1769442209',
    address: 'East Zone',
    estd: '',
  },
  {
    name: "Station Commander Cox's Bazar   ",
    number: '1769442210',
    address: 'East Zone',
    estd: '',
  },
  {
    name: "Intelligence Staff Cox's Bazar  ",
    number: '1769442215',
    address: 'East Zone',
    estd: '',
  },
  {
    name: "Gangway Cox's Bazar  ",
    number: '1769442219',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Sentmartin    ',
    number: '1769442220',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Sentmartin   ',
    number: '1769442225',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Sentmartin   ',
    number: '1769442229',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Kutubdia      ',
    number: '1769442230',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Kutubdia     ',
    number: '1769442235',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Kutubdia     ',
    number: '1769442239',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Moheshkali    ',
    number: '1769442240',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Moheshkhali  ',
    number: '1769442245',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Moheshkhali  ',
    number: '1769442249',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Sandip        ',
    number: '1769442250',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligece Staff Sandip        ',
    number: '1769442255',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Sandip ',
    number: '1769442259',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Teknaf        ',
    number: '1769442260',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Teknaf       ',
    number: '1769442265',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Teknaf ',
    number: '1769442269',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Bhatiari      ',
    number: '1769442270',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Bhatiari     ',
    number: '1769442275',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Bhatiari     ',
    number: '1769442279',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Urirchar      ',
    number: '1769442280',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Urirchar     ',
    number: '1769442285',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Urirchar     ',
    number: '1769442289',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Mirshorai     ',
    number: '1769442290',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Mirshorai    ',
    number: '1769442295',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Mirshorai    ',
    number: '1769442299',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Himchorhi     ',
    number: '1769442300',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Himchorhi    ',
    number: '1769442305',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Himchorhi    ',
    number: '1769442309',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Inani         ',
    number: '1769442310',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligece Staff Inani         ',
    number: '1769442315',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Inani  ',
    number: '1769442319',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Matarbari     ',
    number: '1769442320',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligece Staff Matarbari     ',
    number: '1769442325',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Matarbari    ',
    number: '1769442329',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Patenga       ',
    number: '1769442330',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligece Staff Patenga       ',
    number: '1769442335',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Patenga',
    number: '1769442339',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Station Commander Sahpuri       ',
    number: '1769442340',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligece Staff Sahpuri       ',
    number: '1769442345',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Sahpuri',
    number: '1769442349',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CC Normanspoint',
    number: '1769442350',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligece Staff Normanspoint  ',
    number: '1769442355',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Normanspoint ',
    number: '1769442359',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CC Sonadia Bit ',
    number: '1769442360',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligece Staff Sonadia Bit   ',
    number: '1769442365',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Sonadia Bit  ',
    number: '1769442369',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CC Baharchora  ',
    number: '1769442370',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligece Staff Baharchora',
    number: '1769442375',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Baharchora',
    number: '1769442379',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CC Sarikait    ',
    number: '1769442380',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Intelligece Staff Sarikait      ',
    number: '1769442385',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway Sarikait     ',
    number: '1769442389',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CO CGS Syed Nazrul   ',
    number: '1769442500',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Syed Nazrul  ',
    number: '1769442501',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EO CGS Syed Nazrul   ',
    number: '1769442502',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'SO CGS Syed Nazrul   ',
    number: '1769442503',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'LO CGS Syed Nazrul   ',
    number: '1769442504',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'MO CGS Syed Nazrul   ',
    number: '1769442505',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'NO CGS Syed Nazrul   ',
    number: '1769442506',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'GO CGS Syed Nazrul   ',
    number: '1769442507',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'SCO CGS Syed Nazrul  ',
    number: '1769442508',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'RO CGS Syed Nazrul   ',
    number: '1769442509',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'OOD CGS Syed Nazrul  ',
    number: '1769442510',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Syed Nazrul         ',
    number: '1769442519',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CO CGS Tajuddin',
    number: '1769442520',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Tajuddin     ',
    number: '1769442521',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EO CGS Tajuddin',
    number: '1769442522',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'SO CGS Tajuddin',
    number: '1769442523',
    address: 'East Zone',
    estd: '',
  },
  {
    name: ' LO CGS Tajuddin     ',
    number: '1769442524',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'MO CGS Tajuddin',
    number: '1769442525',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'NO CGS Tajuddin',
    number: '1769442526',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'GO CGS Tajuddin',
    number: '1769442527',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'SCO CGS Tajuddin     ',
    number: '1769442528',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'RO CGS Tajuddin',
    number: '1769442529',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'OOD CGS Tajuddin     ',
    number: '1769442530',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Tajuddin ',
    number: '1769442539',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CO CGS Ruposhi Bangla',
    number: '1769442580',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Ruposhi Bangla          ',
    number: '1769442581',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Ruposhi Bangla      ',
    number: '1769442589',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CO CGS Sabuj Bangla  ',
    number: '1769442590',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Sabuj Bangla ',
    number: '1769442591',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Sabuj Bangla        ',
    number: '1769442599',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CO CGS Shamol Bangla ',
    number: '1769442600',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Shamol Bangla',
    number: '1769442601',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Shamol Bangla       ',
    number: '1769442609',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CO CGS Shet Gang     ',
    number: '1769442660',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Shet Gang    ',
    number: '1769442661',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Shet Gang',
    number: '1769442669',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CO CGS Porte Grande  ',
    number: '1769442670',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Porte Grande ',
    number: '1769442671',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Porte Grande        ',
    number: '1769442679',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CO CGS Sonadia ',
    number: '1769442680',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Sonadia',
    number: '1769442681',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Sonadia  ',
    number: '1769442689',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'CO CGS Kutubdia',
    number: '1769442690',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Kutubdia     ',
    number: '1769442691',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Kutubdia ',
    number: '1769442699',
    address: 'East Zone',
    estd: '',
  },
  {
    name: 'Zonal Commander   ',
    number: '1769443000',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'PA to Zonal Commander   ',
    number: '1769443001',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CSO (Admin)       ',
    number: '1769443005',
    address: 'South Zone',
    estd: '',
  },
  {
    name: "Senior Officer Shop's & Craft      ",
    number: '1769443010',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Staff Officer OPS ',
    number: '1769443333',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Staff OPS         ',
    number: '1769443016',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'OPS Room          ',
    number: '1769443999',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Plans     ',
    number: '1769443020',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Staff Officer LAW ',
    number: '1769443025',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Traning   ',
    number: '1769443030',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Engineering          ',
    number: '1769443035',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Electrical & Arma    ',
    number: '1769443040',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Logistics ',
    number: '1769443045',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'OIC Intelligence  ',
    number: '1769443050',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff',
    number: '1769443051',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff',
    number: '1769443052',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff',
    number: '1769443053',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff',
    number: '1769443054',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Office     ',
    number: '1769443055',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Tender    ',
    number: '1769443060',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Staff Officer signals   ',
    number: '1769443065',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Comsen ',
    number: '1769443066',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Incharge Comsen   ',
    number: '1769443067',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Public Relation Officer ',
    number: '1769443070',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Anti smagling Officer   ',
    number: '1769443075',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Area chairman CGFWA     ',
    number: '1769443080',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Treasurer         ',
    number: '1769443082',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Staff CGFWA office',
    number: '1769443085',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CGPM/Staff Officer Provost         ',
    number: '1769443090',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-1      ',
    number: '1769443091',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-2      ',
    number: '1769443092',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-3      ',
    number: '1769443093',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Duty DR',
    number: '1769443094',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CGPM Office       ',
    number: '1769443095',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Mail man          ',
    number: '1769443099',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Commanding Officer',
    number: '1769443100',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CO Secretery      ',
    number: '1769443101',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CO Secretery Office     ',
    number: '1769443102',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Exicutive Officer ',
    number: '1769443105',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'EXO Staff         ',
    number: '1769443106',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Chief Boson Met   ',
    number: '1769443107',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Boson yeo man     ',
    number: '1769443108',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'OOD    ',
    number: '1769443111',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gunnery Officer   ',
    number: '1769443112',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Ships GI          ',
    number: '1769443113',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gunnery Office    ',
    number: '1769443114',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Regulating Officer',
    number: '1769443115',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Regulating Office ',
    number: '1769443116',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Engineering Officer     ',
    number: '1769443118',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Engineering Office',
    number: '1769443119',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'EO Writer         ',
    number: '1769443120',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Electrical Officer',
    number: '1769443122',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Electrical Office ',
    number: '1769443123',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'LO Writer         ',
    number: '1769443124',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Maintainance Officer    ',
    number: '1769443126',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Maintainance Office     ',
    number: '1769443127',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Senior Medical Officer  ',
    number: '1769443130',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Medical Officer   ',
    number: '1769443131',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Ward Master       ',
    number: '1769443132',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Sick Bay          ',
    number: '1769443133',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Duty Medical Assistant  ',
    number: '1769443134',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Supply Officer    ',
    number: '1769443135',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Store Office      ',
    number: '1769443136',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Pay Office        ',
    number: '1769443137',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Officer In Charge (Boat Pool)      ',
    number: '1769443140',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Boat Pool (cpo/po)',
    number: '1769443141',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Boat Pool         ',
    number: '1769443142',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Incharge Exchange & Server         ',
    number: '1769443143',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Exchange & Server Room  ',
    number: '1769443144',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'MTO    ',
    number: '1769443145',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'MT Chief          ',
    number: '1769443146',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'MT Pool',
    number: '1769443147',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Ward Room Mess Secretery',
    number: '1769443148',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Duty STW          ',
    number: '1769443149',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Mess OIC          ',
    number: '1769443150',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Mess Secretery    ',
    number: '1769443151',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'SOOD   ',
    number: '1769443160',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CPOOD/POOD        ',
    number: '1769443162',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Guard Room        ',
    number: '1769443166',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Nizampur         ',
    number: '1769443200',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Nizampur        ',
    number: '1769443205',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Nizampur  ',
    number: '1769443209',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Patharghata      ',
    number: '1769443210',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Patharghata     ',
    number: '1769443215',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Patharghata     ',
    number: '1769443219',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Patuakhali       ',
    number: '1769443220',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Patuakhali      ',
    number: '1769443225',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Patuakhali',
    number: '1769443229',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Hatia ',
    number: '1769443230',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Hatia',
    number: '1769443235',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Hatia     ',
    number: '1769443239',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Laxmipur         ',
    number: '1769443240',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Laxmipur        ',
    number: '1769443245',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Laxmipur  ',
    number: '1769443249',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Nidrasokhina     ',
    number: '1769443250',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Nidrasokhina    ',
    number: '1769443255',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Nidrasokhina    ',
    number: '1769443259',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Barishal         ',
    number: '1769443260',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Barishal        ',
    number: '1769443265',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Barishal  ',
    number: '1769443269',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Kaligonj         ',
    number: '1769443270',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Kaligonj        ',
    number: '1769443275',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Kaligonj  ',
    number: '1769443279',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Hizla ',
    number: '1769443280',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Hizla',
    number: '1769443285',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Hizla     ',
    number: '1769443289',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Payra ',
    number: '1769443290',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Payra',
    number: '1769443295',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Payra     ',
    number: '1769443299',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Kuakata          ',
    number: '1769443300',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Kuakata         ',
    number: '1769443305',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Kuakata   ',
    number: '1769443309',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Station Commander Charfession      ',
    number: '1769443310',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Charfession     ',
    number: '1769443315',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Charfession     ',
    number: '1769443319',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CC Ramgati        ',
    number: '1769443320',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Ramgati         ',
    number: '1769443325',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Ramgati   ',
    number: '1769443329',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CC Tazumuddin     ',
    number: '1769443330',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Tazumuddin      ',
    number: '1769443335',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Tazumuddin',
    number: '1769443339',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CC Chormanika     ',
    number: '1769443340',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Chormanika      ',
    number: '1769443345',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Chormanika',
    number: '1769443349',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CC Rangabali      ',
    number: '1769443350',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Rangabali       ',
    number: '1769443355',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Rangabali ',
    number: '1769443359',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'CC Monpura        ',
    number: '1769443360',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Monpura         ',
    number: '1769443365',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway Monpura   ',
    number: '1769443369',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'OIC CGS Pabna     ',
    number: '1769443500',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Pabna ',
    number: '1769443509',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'OIC CGS Noakhali  ',
    number: '1769443510',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Noakhali    ',
    number: '1769443519',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'OIC CGS Patuakhali',
    number: '1769443520',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Patuakhali  ',
    number: '1769443529',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'OIC CGS Bagura    ',
    number: '1769443530',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Bagura',
    number: '1769443539',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'OIC HPB Balesshor ',
    number: '1769443540',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway HPB Balesshor   ',
    number: '1769443549',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'OIC HPB Tetulia   ',
    number: '1769443550',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway HPB Tetulia     ',
    number: '1769443559',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'OIC HPB Buriganga ',
    number: '1769443560',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway HPB Buriganga   ',
    number: '1769443569',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'OIC HPB Shitolaxma',
    number: '1769443570',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Gangway HPB Shitolaxma  ',
    number: '1769443579',
    address: 'South Zone',
    estd: '',
  },
  {
    name: 'Zonal Commander ',
    number: '1769444000',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'PA to Zonal Commander ',
    number: '1769444001',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CSO (Admin)     ',
    number: '1769444005',
    address: 'West Zone',
    estd: '',
  },
  {
    name: "Senior Officer Shop's & Craft    ",
    number: '1769444010',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Staff Officer OPS     ',
    number: '1769444333',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Staff OPS       ',
    number: '1769444016',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'OPS Room        ',
    number: '1769444999',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Plans   ',
    number: '1769444020',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Staff Officer LAW     ',
    number: '1769444025',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Traning ',
    number: '1769444030',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Engineering        ',
    number: '1769444035',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Electrical & Arma  ',
    number: '1769444040',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Logistics          ',
    number: '1769444045',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'OIC Intelligence',
    number: '1769444050',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff    ',
    number: '1769444051',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff    ',
    number: '1769444052',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff    ',
    number: '1769444053',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff    ',
    number: '1769444054',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Office   ',
    number: '1769444055',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Staff Officer Tender  ',
    number: '1769444060',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Staff Officer signals ',
    number: '1769444065',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Comsen          ',
    number: '1769444066',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Incharge Comsen ',
    number: '1769444067',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Public Relation Officer          ',
    number: '1769444070',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Anti smagling Officer ',
    number: '1769444075',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Area chairman CGFWA   ',
    number: '1769444080',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Treasurer       ',
    number: '1769444082',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Staff CGFWA office    ',
    number: '1769444085',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CGPM/Staff Officer Provost       ',
    number: '1769444090',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-1    ',
    number: '1769444091',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-2    ',
    number: '1769444092',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CGPM Staff-3    ',
    number: '1769444093',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Duty DR         ',
    number: '1769444094',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CGPM Office     ',
    number: '1769444095',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Mail man        ',
    number: '1769444099',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Commanding Officer    ',
    number: '1769444100',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CO Secretery    ',
    number: '1769444101',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CO Secretery Office   ',
    number: '1769444102',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Exicutive Officer     ',
    number: '1769444105',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'EXO Staff       ',
    number: '1769444106',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Chief Boson Met ',
    number: '1769444107',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Boson yeo man   ',
    number: '1769444108',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gunnery Officer ',
    number: '1769444112',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Ships GI        ',
    number: '1769444113',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gunnery Office  ',
    number: '1769444114',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Regulating Officer    ',
    number: '1769444115',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Regulating Office     ',
    number: '1769444116',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Engineering Officer   ',
    number: '1769444118',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Engineering Office    ',
    number: '1769444119',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'EO Writer       ',
    number: '1769444120',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Electrical Officer    ',
    number: '1769444122',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Electrical Office     ',
    number: '1769444123',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'LO Writer       ',
    number: '1769444124',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Maintainance Officer  ',
    number: '1769444126',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Maintainance Office   ',
    number: '1769444127',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Senior Medical Officer',
    number: '1769444130',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Medical Officer ',
    number: '1769444131',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Ward Master     ',
    number: '1769444132',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Sick Bay        ',
    number: '1769444133',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Duty Medical Assistant',
    number: '1769444134',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Supply Officer  ',
    number: '1769444135',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Store Office    ',
    number: '1769444136',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Pay Office      ',
    number: '1769444137',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Officer In Charge (Boat Pool)    ',
    number: '1769444140',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Boat Pool (cpo/po)    ',
    number: '1769444141',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Boat Pool       ',
    number: '1769444142',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Incharge Exchange & Server       ',
    number: '1769444143',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Exchange & Server Room',
    number: '1769444144',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'MTO  ',
    number: '1769444145',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'MT Chief        ',
    number: '1769444146',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'MT Pool         ',
    number: '1769444147',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Ward Room Mess Secretery         ',
    number: '1769444148',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Duty STW        ',
    number: '1769444149',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Mess OIC        ',
    number: '1769444150',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Mess Secretery  ',
    number: '1769444151',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'OOD  ',
    number: '1769444111',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CPOOD/POOD      ',
    number: '1769444165',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Guard Room      ',
    number: '1769444166',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Station Commander Koyra          ',
    number: '1769444200',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Koyra         ',
    number: '1769444205',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Koyra   ',
    number: '1769444209',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Station Commander Shoronkhola    ',
    number: '1769444210',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Shoronkhola   ',
    number: '1769444215',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Shoronkhola   ',
    number: '1769444219',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Station Commander Koikhali       ',
    number: '1769444220',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Koikhali      ',
    number: '1769444225',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Koikhali',
    number: '1769444229',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Station Commander Rupsha         ',
    number: '1769444230',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Rupsha        ',
    number: '1769444235',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Rupsha  ',
    number: '1769444239',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Station Commander Shopoti        ',
    number: '1769444240',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Shopoti       ',
    number: '1769444245',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Shopoti ',
    number: '1769444249',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Station Commander Kokilmoni      ',
    number: '1769444250',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Kokilmoni     ',
    number: '1769444255',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Kokilmoni     ',
    number: '1769444259',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Station Commander Dobeki         ',
    number: '1769444260',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Dobeki        ',
    number: '1769444265',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Dobeki  ',
    number: '1769444269',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Station Commander Poshpokathi    ',
    number: '1769444270',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Poshpokath    ',
    number: '1769444275',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Poshpokath    ',
    number: '1769444279',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Station Commander Kagadobeki     ',
    number: '1769444280',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Kagadobeki    ',
    number: '1769444285',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway  Kagadobeki   ',
    number: '1769444289',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Station Commander Harbaria       ',
    number: '1769444290',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Harbaria      ',
    number: '1769444295',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Harbaria',
    number: '1769444299',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CC Kochikhali   ',
    number: '1769444300',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Kochikhali    ',
    number: '1769444305',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Kochikhali    ',
    number: '1769444309',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CC Nolian       ',
    number: '1769444310',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Nolian        ',
    number: '1769444315',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Nolian  ',
    number: '1769444319',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CC Dublarchor   ',
    number: '1769444320',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Intelligence Staff Dublarchor    ',
    number: '1769444325',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway Dublarchor    ',
    number: '1769444329',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CO CGS Monsur Ali     ',
    number: '1769444500',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Monsur Ali    ',
    number: '1769444501',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'EO CGS Monsur Ali     ',
    number: '1769444502',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'SO CGS Monsur Ali     ',
    number: '1769444503',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'LO CGS Monsur Ali     ',
    number: '1769444504',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'MO CGS Monsur Ali     ',
    number: '1769444505',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'NO CGS Monsur Ali     ',
    number: '1769444506',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'GO CGS Monsur Ali     ',
    number: '1769444507',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'SCO CGS Monsur Ali    ',
    number: '1769444508',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'RO CGS Monsur Ali     ',
    number: '1769444509',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'OOD CGS Monsur Ali    ',
    number: '1769444510',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Monsur Ali',
    number: '1769444519',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CO CGS Kamarozzman    ',
    number: '1769444520',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Kamarozzman   ',
    number: '1769444521',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'EO CGS Kamarozzman    ',
    number: '1769444522',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'SO CGS Kamarozzman    ',
    number: '1769444523',
    address: 'West Zone',
    estd: '',
  },
  {
    name: ' LO CGS Kamarozzman   ',
    number: '1769444524',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'MO CGS Kamarozzman    ',
    number: '1769444525',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'NO CGS Kamarozzman    ',
    number: '1769444526',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'GO CGS Kamarozzman    ',
    number: '1769444527',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'SCO CGS Kamarozzman   ',
    number: '1769444528',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'RO CGS Kamarozzman    ',
    number: '1769444529',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'OOD CGS Kamarozzman   ',
    number: '1769444530',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Kamarozzman          ',
    number: '1769444539',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CO CGS Touhid   ',
    number: '1769444610',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Touhid  ',
    number: '1769444611',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Touhid    ',
    number: '1769444619',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CO CGS Tawfik   ',
    number: '1769444620',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Tawfik  ',
    number: '1769444621',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Tawfik    ',
    number: '1769444629',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CO CGS Tamzid   ',
    number: '1769444630',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Tamzid  ',
    number: '1769444631',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Tamzid    ',
    number: '1769444639',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'CO CGS Tanveer  ',
    number: '1769444640',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'EXO CGS Tanveer ',
    number: '1769444641',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway CGS Tanveer   ',
    number: '1769444649',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'OIC HSPV Gorai  ',
    number: '1769444650',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway HSPV Gorai    ',
    number: '1769444659',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'OIC HSPV Atrai  ',
    number: '1769444660',
    address: 'West Zone',
    estd: '',
  },
  {
    name: 'Gangway HSPV Atrai    ',
    number: '1769444669',
    address: 'West Zone',
    estd: '',
  },

  {
    name: 'Commandant',
    number: '1769446000',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'PA to Commandant',
    number: '1769446001',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Deputy Commandent ',
    number: '1769446010',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'OPS Room     ',
    number: '1769446999',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'OIC Intelligence  ',
    number: '1769446050',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Intelligence Staff',
    number: '1769446051',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Intelligence Office ',
    number: '1769446055',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Staff Officer Tender',
    number: '1769446060',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Staff Officer signals',
    number: '1769446065',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Comsen ',
    number: '1769446066',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Incharge Comsen   ',
    number: '1769446067',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Public Relation Officer',
    number: '1769446070',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Anti smagling Officer',
    number: '1769446075',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Area chairman CGFWA ',
    number: '1769446080',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Treasurer ',
    number: '1769446081',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Staff CGFWA office',
    number: '1769446085',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'CGPM/Staff Officer Provost    ',
    number: '1769446090',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'CGPM Staff-1 ',
    number: '1769446091',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'CGPM Staff-2 ',
    number: '1769446092',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'CGPM Staff-3 ',
    number: '1769446093',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Duty DR',
    number: '1769446094',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'CGPM Office  ',
    number: '1769446095',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Mail man     ',
    number: '1769446099',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Exicutive Officer ',
    number: '1769446105',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'EXO Staff    ',
    number: '1769446106',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Chief Boson Met   ',
    number: '1769446107',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Boson yeo man',
    number: '1769446108',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Gunnery Officer   ',
    number: '1769446112',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Ships GI     ',
    number: '1769446113',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Gunnery Office    ',
    number: '1769446114',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Regulating Officer',
    number: '1769446115',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Regulating Office ',
    number: '1769446116',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Engineering Officer ',
    number: '1769446118',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Engineering Office',
    number: '1769446119',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'EO Writer    ',
    number: '1769446120',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Electrical Officer',
    number: '1769446122',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Electrical Office ',
    number: '1769446123',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'LO Writer    ',
    number: '1769446124',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Maintainance Officer',
    number: '1769446126',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Maintainance Office ',
    number: '1769446127',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Senior Medical Officer  ',
    number: '1769446130',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Medical Officer   ',
    number: '1769446131',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Ward Master  ',
    number: '1769446132',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Sick Bay     ',
    number: '1769446133',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Duty Medical Assistant  ',
    number: '1769446134',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Supply Officer    ',
    number: '1769446135',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Store Office ',
    number: '1769446136',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Pay Office   ',
    number: '1769446137',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Officer In Charge (Boat Pool) ',
    number: '1769446140',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Boat Pool (cpo/po)',
    number: '1769446141',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Boat Pool    ',
    number: '1769446142',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Incharge Exchange & Server    ',
    number: '1769446143',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Exchange & Server Room  ',
    number: '1769446144',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'MTO',
    number: '1769446145',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'MT Chief     ',
    number: '1769446146',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'MT Pool',
    number: '1769446147',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Ward Room Mess Secretery',
    number: '1769446148',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Duty STW     ',
    number: '1769446149',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Mess OIC     ',
    number: '1769446150',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Mess Secretery    ',
    number: '1769446151',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'OOD',
    number: '1769446111',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'CPOOD/POOD   ',
    number: '1769446165',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Guard Room   ',
    number: '1769446166',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'Traning commander ',
    number: '1769446170',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'traning chief',
    number: '1769446175',
    address: 'Agrajatra',
    estd: '',
  },
  {
    name: 'traning Office    ',
    number: '1769446176',
    address: 'Agrajatra',
    estd: '',
  },
]
